theme: jekyll-theme-minimal
title: Kaysan Merchant

baseurl: "/TER"

plugins:
  - jekyll-feed
  - jekyll-paginate

markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"